name: Train Model and Deploy Application

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push a la rama 'main'

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias

    - name: Run the training notebook
      run: |
        pip install jupyter nbconvert
        jupyter nbconvert --to notebook --execute --inplace path_to_your_notebook.ipynb

  deploy_application:
    runs-on: ubuntu-latest
    needs: train_model  # Este job se ejecuta despu√©s de que se complete el entrenamiento del modelo

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt  # Reinstala las dependencias si es necesario

    - name: Run script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python streamlit_app.py

